### ISSUE TITLE
Unable to find template: js

### ISSUE THREAD

**Issue by guttume** [neutralinojs/neutralinojs-cli-appify#4]
I am trying to use the command `neu appify --title "MoviesZri" https://codezri.org/movieszri` and I am getting error `Unable to find template: js`. I am getting this error for any website.

**Comment by shalithasuranga** [comment]
Thanks for reporting. I will apply a fix. This issue is occured because the CLI had some changes recently

**Comment by shalithasuranga** [comment]
Fixed with the latest version
