### ISSUE TITLE
Fix process exit issue

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs-cli-appify#5]

**Comment by georgechitechi** [comment]
Hi @shalithasuranga.
Nice plugin

Not sure if you got any fix for this process exit issue.

**Comment by shalithasuranga** [comment]
Hi.. @georgechitechi  Thanks for checking :) .. sure I will check this and apply necessary fixes soon :)

**Comment by NethmiRodrigo** [comment]
Hi! @shalithasuranga can I be assigned to this?

**Comment by shalithasuranga** [comment]
Sure @NethmiRodrigo .. Thanks
