### ISSUE TITLE
Add the CHANGELOG.md file

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs-cli-appify#7]
Use the changelog format recommended by ReleaseZri (You can copy-paste from other repos)

**Comment by Jassi10000-zz** [comment]
@shalithasuranga Sir pls review my contribution

**Comment by Ayman161803** [comment]
This issue has been solved by PR #9. We might want to close this.

**Comment by shalithasuranga** [comment]
Yeah, let's close this one -- thanks for reminding about it :tada:
